body:
  - type: input
    id: specs_version
    attributes:
      label: "STMViewer Version/Branch:"
      value: "Version 0.X.Y, Branch: XXX (main/devel/etc.)"
      placeholder: "Version 0.4.0, Branch: main"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: "Operating system:"
      placeholder: "e.g. Windows 11, Ubuntu 22.04"
    validations:
      required: true
  - type: input
    id: probe
    attributes:
      label: "Debug probe:"
      placeholder: "e.g. ST-Link V2, ST-Link V3 MINIE, J-Link Ultra"
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: "Details:"
      description: "Please describe the problem/enhancement in detail."
      value: |
        **My Issue/Question:**

        Please provide as much context as possible
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots/Video:"
      description: "Attach screenshots or gif/videos to clarify the context. They often convey useful information that is omitted by the description."
      placeholder: "(Drag files here)"
    validations:
      required: false
